# Generated by Django 6.0.1 on 2026-05-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
    ]
