# Generated by Django 6.0.1 on 2026-05-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0003_bikedesign_testride'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bikedesign',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bike Design', 'verbose_name_plural': 'Bike Designs'},
        ),
        migrations.AddField(
            model_name='bikedesign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the design was last updated'),
        ),
        migrations.AlterField(
            model_name='bikedesign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the design was created'),
        ),
        migrations.AlterField(
            model_name='bikedesign',
            name='design_data',
            field=models.TextField(help_text='Canvas drawing data as base64 PNG'),
        ),
        migrations.AlterField(
            model_name='bikedesign',
            name='name',
            field=models.CharField(help_text='Name of the bike design', max_length=100),
        ),
    ]
