# Generated by Django 6.0.1 on 2026-05-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0004_alter_bikedesign_options_bikedesign_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
